In [1]:
import numpy as np

In [6]:
myarr = np.array([[3,5,6,7]],np.int64)

In [9]:
myarr[0,2]

6

In [10]:
myarr.shape

(1, 4)

In [11]:
myarr.dtype

dtype('int64')

In [13]:
list = np.array([[2,4,5,6],[4,7,2,1],[3,8,4,9]])

In [14]:
list

array([[2, 4, 5, 6],
       [4, 7, 2, 1],
       [3, 8, 4, 9]])

In [15]:
list[2,3] = 45

In [16]:
list

array([[ 2,  4,  5,  6],
       [ 4,  7,  2,  1],
       [ 3,  8,  4, 45]])

In [17]:
np.array({2,3,5})

array({2, 3, 5}, dtype=object)

In [18]:
zeros = np.zeros((2,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng = np.arange(10)

In [22]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
lspace = np.linspace(1,10,10)

In [31]:
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
emp = np.empty((4,5))

In [34]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219578e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 2.78149851e-307, 1.06811422e-306,
        8.45590539e-307, 6.23054972e-307],
       [9.34609790e-307, 1.78019354e-306, 1.69119330e-306,
        1.24611470e-306, 2.56765117e-312]])

In [35]:
emp_like = np.empty_like(lspace)

In [36]:
emp_like

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
ide = np.identity(23)

In [38]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0.,

In [39]:
ide.size


529

In [40]:
ide.shape

(23, 23)

In [41]:
tutu = np.arange(99)

In [42]:
tutu

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
tutu.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [44]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [45]:
ar = np.array(x)

In [46]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [48]:
ar.sum(axis=0)

array([12, 15, 18])

In [51]:
g = ar.T


In [52]:
g

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
g.sum(axis=0)

array([ 6, 15, 24])

In [54]:
g.flat


In [55]:
for item in g.flat:
    print(item)

1
4
7
2
5
8
3
6
9


In [56]:
g.ndim


2

In [58]:
one = np.array([1,4,6,1,3,44,3,22,])

In [59]:
one.argmax()

5

In [60]:
one.argmin()

0

In [61]:
one.argsort()

array([0, 3, 4, 6, 1, 2, 7, 5], dtype=int64)

In [63]:
g.argmax()

8

In [64]:
g.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [65]:
g.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [66]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
f = np.array([[1, 5, 7],
       [1, 0, 3],
       [7, 5, 2]])

In [68]:
ar+f

array([[ 2,  7, 10],
       [ 5,  5,  9],
       [14, 13, 11]])

In [69]:
ar*f

array([[ 1, 10, 21],
       [ 4,  0, 18],
       [49, 40, 18]])

In [73]:
h = ar+(ar*f)

In [74]:
np.sqrt(h)

array([[1.41421356, 3.46410162, 4.89897949],
       [2.82842712, 2.23606798, 4.89897949],
       [7.48331477, 6.92820323, 5.19615242]])

In [75]:
h

array([[ 2, 12, 24],
       [ 8,  5, 24],
       [56, 48, 27]])

In [78]:
type(np.where(h>10))

tuple

In [ ]:
np